"""Parse AI draft output into structured data.

Extracts:
- sections: dict mapping "## N. Title" -> content (as written, human-readable)
- rubric: dict with novelty/leverage/evidence/cost/moat/adoption/overall
- raw_md: the full raw output (unchanged, for direct rendering)
"""
import re
from typing import Any

# Section headings generated by ai_generate_pnote_draft (must match prompt exactly)
_PNOTE_SECTION_HEADINGS = [
    "1. 背景",
    "2. 核心问题",
    "3. 方法结构",
    "4. 关键创新",
    "5. 实验分析",
    "6. 对抗式审稿",
    "7. 优势",
    "8. 局限",
    "9. 本质抽象",
    "10. 与其他方法对比",
    "11. Decision（决策）",
    "12. 知识蒸馏",
    "13. 认知升级",
    "14. 评分量表",
]

# Subsections under "3. 方法结构" and "5. 实验分析"
_SECTION_SUBSECTIONS = {
    "3. 方法结构": ["3.1 架构拆解", "3.2 算法逻辑", "3.3 关键组件"],
    "5. 实验分析": ["5.1 数据集", "5.2 基线对比", "5.3 消融实验", "5.4 成本分析"],
}

# Subsections under "12. 知识蒸馏"
_KNOWLEDGE_DISTRACTION_SUBSECTIONS = ["Facts", "Principles", "Insights"]

# Regex patterns for rubric extraction
_RUBRIC_BLOCK_RE = re.compile(
    r'<!--\s*\n<RUBRIC>\s*\n(.*?)\n</RUBRIC>\s*\n-->',
    re.DOTALL,
)
_RUBRIC_JSON_RE = re.compile(
    r'\{[^{}]*"novelty"[^{}]*"leverage"[^{}]*"evidence"[^{}]*\}',
    re.DOTALL,
)


def parse_ai_pnote_draft(raw: str) -> tuple[dict[str, str], dict[str, Any], str]:
    """
    Parse AI P-note draft into structured sections + rubric.

    Args:
        raw: Raw markdown output from LLM (including XML comment block).

    Returns:
        (sections_dict, rubric_dict, raw_md)
        sections_dict: {"## N. Title": "content..."}
        rubric_dict: {"novelty": 3, "leverage": 4, ...}
        raw_md: unchanged input (for direct rendering)
    """
    rubric = _parse_rubric(raw)
    sections = _parse_sections(raw)
    return sections, rubric, raw


def _parse_rubric(raw: str) -> dict[str, Any]:
    """Extract rubric dict from XML comment block."""
    rubric: dict[str, Any] = {}

    # Try full XML block first
    m = _RUBRIC_BLOCK_RE.search(raw)
    if m:
        json_str = m.group(1).strip()
        return _parse_rubric_json(json_str)

    # Fallback: search for JSON object anywhere
    m = _RUBRIC_JSON_RE.search(raw)
    if m:
        return _parse_rubric_json(m.group(0))

    # Fallback: individual score lines
    # For each keyword, find the score on that line.
    # Take the FIRST integer after the colon (the actual score).
    # Handles "novelty: 3 (1-5)" → 3, "novelty: 3" → 3.
    # Also handles single-quoted JSON: "key": '3'
    for key in ["novelty", "leverage", "evidence", "cost", "moat", "adoption"]:
        for line in raw.split('\n'):
            if key.lower() not in line.lower():
                continue
            # Extract first integer after key-specific colon (handles "leverage": "4" on same line as "novelty": '3')
            m = re.search(rf'"{key}"\s*:\s*[\"\']?(\d)[\"\']?', line, re.IGNORECASE)
            if m:
                rubric[key] = int(m.group(1))
                break
            # Fallback: digit after ) and colon (handles "* Novelty (1-5): 5")
            m2 = re.search(r'\)\s*:\s*(\d)', line)
            if m2:
                rubric[key] = int(m2.group(1))
                break
            # Fallback: first integer after colon (handles "novelty: 3 (1-5)")
            m3 = re.search(r':\s*(\d)', line)
            if m3:
                rubric[key] = int(m3.group(1))
                break

    overall_m = re.search(r'overall.*?judgment[:：]\s*(.{5,100})', raw, re.IGNORECASE)
    if overall_m:
        rubric["overall"] = overall_m.group(1).strip()

    return rubric


def _parse_rubric_json(json_str: str) -> dict[str, Any]:
    """Parse rubric JSON, handling common LLM mistakes."""
    # Remove trailing comma before }
    json_str = re.sub(r',(\s*})', r'\1', json_str)
    # Try to fix unquoted keys
    try:
        import json
        return json.loads(json_str)
    except Exception:
        pass

    # Try extracting individual values
    rubric: dict[str, Any] = {}
    for key in ["novelty", "leverage", "evidence", "cost", "moat", "adoption"]:
        m = re.search(rf'"{key}"\s*:\s*["\']?(\d)["\']?', json_str, re.IGNORECASE)
        if m:
            rubric[key] = int(m.group(1))

    overall_m = re.search(r'"overall"\s*:\s*"(.*?)"', json_str, re.DOTALL)
    if overall_m:
        rubric["overall"] = overall_m.group(1).strip()

    return rubric


def _parse_sections(raw: str) -> dict[str, str]:
    """
    Split raw markdown by ## headings into sections.
    Returns dict {"## N. Title": "content..."}.
    Subsections (###) are embedded in parent content AND also extracted as separate keys.
    """
    sections: dict[str, str] = {}

    # Find all ## headings with their positions
    heading_positions: list[tuple[int, str]] = []
    for m in re.finditer(r'^##\s+(.+)$', raw, re.MULTILINE):
        heading_positions.append((m.start(), m.group(1).strip()))

    if not heading_positions:
        return {}

    for i, (start, title) in enumerate(heading_positions):
        end = heading_positions[i + 1][0] if i + 1 < len(heading_positions) else len(raw)
        block = raw[start:end]
        # Split off the heading line, keep rest
        first_newline = block.find('\n')
        content = block[first_newline + 1:].strip() if first_newline >= 0 else ""

        # Extract ### subsections as separate keys
        subsection_positions: list[tuple[int, str]] = []
        for sm in re.finditer(r'^###\s+(.+)$', content, re.MULTILINE):
            subsection_positions.append((sm.start(), sm.group(1).strip()))

        subsection_content_blocks: dict[str, str] = {}
        if subsection_positions:
            # Build pattern to strip all subsections at once (removing from end avoids position shift)
            patterns_to_remove: list[tuple[int, int]] = []
            for j, (ss_start, ss_title) in enumerate(subsection_positions):
                ss_end = subsection_positions[j + 1][0] if j + 1 < len(subsection_positions) else len(content)
                ss_block = content[ss_start:ss_end]
                ssn = ss_block.find('\n')
                ss_content = ss_block[ssn + 1:].strip() if ssn >= 0 else ""
                subsection_content_blocks[f"## {ss_title}"] = ss_content
                patterns_to_remove.append((ss_start, ss_end))
            # Remove subsections from end to start to avoid position shifting
            for ss_start, ss_end in reversed(patterns_to_remove):
                content = content[:ss_start] + content[ss_end:]

        sections[f"## {title}"] = content.strip()
        sections.update(subsection_content_blocks)

    return sections


def extract_rubric_scores(rubric: dict[str, Any]) -> dict[str, int]:
    """Extract integer scores from rubric, returning only valid ones."""
    score_keys = ["novelty", "leverage", "evidence", "cost", "moat", "adoption"]
    result = {}
    for k in score_keys:
        v = rubric.get(k)
        if isinstance(v, int) and 1 <= v <= 5:
            result[k] = v
    return result
