"""Tier 2 unit tests — research_loop.py, pure functions + mocked I/O."""
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

from core import Paper
from research_loop import _build_research_note, run_research


# =============================================================================
# _build_research_note — pure markdown builder
# =============================================================================


class TestBuildResearchNote:
    def _paper(self, **overrides):
        kwargs = dict(
            source="arxiv",
            uid="2301.12345",
            title="Test Paper Title",
            authors=["Alice Smith", "Bob Jones"],
            abstract="This is the abstract of the test paper.",
            published="2023-06-01",
            updated="2023-07-15",
            abs_url="https://arxiv.org/abs/2301.12345",
            pdf_url="https://arxiv.org/pdf/2301.12345.pdf",
        )
        kwargs.update(overrides)
        return Paper(**kwargs)

    def test_basic_metadata_renders(self):
        paper = self._paper()
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        lines = note.split("\n")

        assert "# Test Paper Title" in lines
        assert "**UID:** `2301.12345`" in lines
        assert "**Source:** [arxiv](https://arxiv.org/abs/2301.12345)" in lines
        assert "**PDF:** [https://arxiv.org/pdf/2301.12345.pdf](https://arxiv.org/pdf/2301.12345.pdf)" in lines
        assert "**Published:** 2023-06-01" in lines
        assert "**Updated:** 2023-07-15" in lines
        assert "**Authors:** Alice Smith, Bob Jones" in lines
        assert "## Abstract" in lines
        assert "This is the abstract of the test paper." in lines
        import datetime as dt
        assert f"_Generated by ai-research-os on {dt.date.today().isoformat()}_" in note

    def test_truncates_authors_list_at_5(self):
        paper = self._paper(authors=["A", "B", "C", "D", "E", "F", "G"])
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "A, B, C, D, E et al. (+2 more)" in note

    def test_handles_empty_authors(self):
        paper = self._paper(authors=[])
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "**Authors:**" not in note

    def test_handles_missing_published_updated(self):
        paper = self._paper(published="", updated="")
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "**Published:** N/A" in note
        assert "**Updated:** N/A" in note

    def test_categories_render(self):
        paper = self._paper(categories="cs.AI, cs.LG, cs.CL")
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "**Categories:** cs.AI, cs.LG, cs.CL" in note

    def test_tags_render(self):
        paper = self._paper()
        note = _build_research_note(paper, draft="", rubric={}, tags=["LLM", "Reasoning"])
        assert "**Tags:** LLM, Reasoning" in note

    def test_comment_renders(self):
        paper = self._paper(comment="15 pages, 8 figures, 3 tables")
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "**arXiv Comment:** 15 pages, 8 figures, 3 tables" in note

    def test_journal_ref_renders(self):
        paper = self._paper(journal_ref="Nature 2023")
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "**Journal Ref:** Nature 2023" in note

    def test_no_ai_fallback_message(self):
        paper = self._paper()
        note = _build_research_note(paper, draft="", rubric={}, tags=[])
        assert "_Note: Set `OPENAI_API_KEY` to enable AI draft generation._" in note

    def test_ai_note_section_with_draft(self):
        paper = self._paper()
        note = _build_research_note(
            paper,
            draft="This is the AI-generated research note body.",
            rubric={},
            tags=[],
        )
        assert "## AI Research Note" in note
        assert "This is the AI-generated research note body." in note

    def test_rubric_scores_render_as_stars(self):
        paper = self._paper()
        note = _build_research_note(
            paper,
            draft="Novel approach.",
            rubric={"novelty": 4, "leverage": 3},
            tags=[],
        )
        assert "### Rubric Scores" in note
        assert "**Novelty:** ★★★★☆ (4/5)" in note
        assert "**Leverage:** ★★★☆☆ (3/5)" in note

    def test_overall_score_renders(self):
        paper = self._paper()
        note = _build_research_note(
            paper,
            draft="Good work.",
            rubric={"novelty": 5, "overall": "Strong Accept"},
            tags=[],
        )
        assert "- **Overall:** Strong Accept" in note


# =============================================================================
# run_research — integration with mocked sub-modules
# =============================================================================


class TestRunResearch:
    @pytest.fixture
    def sample_paper(self):
        return Paper(
            source="arxiv",
            uid="2301.12345",
            title="Attention Is All You Need",
            authors=["Ashish Vaswani", "Noam Shazeer"],
            abstract="We propose a new neural network architecture.",
            published="2017-06-12",
            updated="2017-06-12",
            abs_url="https://arxiv.org/abs/1706.03762",
            pdf_url="https://arxiv.org/pdf/1706.03762.pdf",
        )

    @pytest.fixture
    def tmp_output_dir(self):
        with tempfile.TemporaryDirectory() as d:
            yield Path(d)

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core._download_pdf")
    @patch("research_loop.core.extract_pdf_text")
    @patch("research_loop.core.ai_generate_pnote_draft")
    @patch("research_loop.core.time.sleep")
    def test_full_pipeline_creates_note(
        self, mock_sleep, mock_draft, mock_extract, mock_dl, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]
        mock_extract.return_value = "Extracted PDF text here."
        mock_draft.return_value = "AI draft content."

        paths = run_research(
            query="transformer attention",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="test-key",
            download_pdfs=True,
            skip_existing=True,
            verbose=False,
        )

        assert len(paths) == 1
        assert paths[0].exists()
        assert "Attention Is All You Need" in paths[0].read_text(encoding="utf-8")

        mock_dl.assert_called_once()
        mock_extract.assert_called_once()
        mock_draft.assert_called_once()

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core.time.sleep")
    def test_no_api_key_skips_ai_draft(
        self, mock_sleep, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]

        with pytest.warns(UserWarning, match="OPENAI_API_KEY not set"):
            paths = run_research(
                query="transformer",
                limit=5,
                output_dir=tmp_output_dir,
                api_key="",
                download_pdfs=False,
                skip_existing=True,
                verbose=True,
            )

        assert len(paths) == 1
        note_text = paths[0].read_text(encoding="utf-8")
        assert "_Note: Set `OPENAI_API_KEY` to enable AI draft generation._" in note_text

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core._download_pdf")
    @patch("research_loop.core.extract_pdf_text")
    @patch("research_loop.core.time.sleep")
    def test_no_extracted_text_skips_ai_draft(
        self, mock_sleep, mock_extract, mock_dl, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]
        mock_extract.side_effect = Exception("PDF corrupted")

        paths = run_research(
            query="transformer",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="test-key",
            download_pdfs=True,
            skip_existing=True,
            verbose=True,
        )

        assert len(paths) == 1
        note_text = paths[0].read_text(encoding="utf-8")
        assert "_Note: Set `OPENAI_API_KEY` to enable AI draft generation._" in note_text

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core.time.sleep")
    def test_skip_existing_note(
        self, mock_sleep, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]

        # Pre-create the note (simulate existing)
        uid_filename = "2301.12345_Attention-Is-All-You-Need.md"
        note_path = tmp_output_dir / uid_filename
        note_path.write_text("Already exists", encoding="utf-8")

        paths = run_research(
            query="transformer",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="",
            download_pdfs=False,
            skip_existing=True,
            verbose=True,
        )

        # Note was skipped (not overwritten)
        assert len(paths) == 1
        assert paths[0] == note_path
        assert note_path.read_text(encoding="utf-8") == "Already exists"

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core._download_pdf")
    @patch("research_loop.core.extract_pdf_text")
    @patch("research_loop.core.ai_generate_pnote_draft")
    @patch("research_loop.core.time.sleep")
    def test_no_skip_regenerates(
        self, mock_sleep, mock_draft, mock_extract, mock_dl, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]
        mock_extract.return_value = "Fresh text."
        mock_draft.return_value = "Fresh draft."

        # Pre-create old note
        uid = sample_paper.uid
        note_path = tmp_output_dir / f"{uid}_note.md"
        note_path.write_text("Old content", encoding="utf-8")

        paths = run_research(
            query="transformer",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="test-key",
            download_pdfs=True,
            skip_existing=False,
            verbose=False,
        )

        assert len(paths) == 1
        assert "Old content" not in paths[0].read_text(encoding="utf-8")

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    def test_empty_result_returns_empty_list(self, mock_search, tmp_output_dir):
        mock_search.return_value = []

        paths = run_research(
            query="nonexistent query xyz abc 123",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="",
            download_pdfs=False,
            verbose=False,
        )

        assert paths == []

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    def test_search_error_returns_empty(self, mock_search, tmp_output_dir):
        mock_search.side_effect = RuntimeError("Network error")

        paths = run_research(
            query="test",
            limit=5,
            output_dir=tmp_output_dir,
            verbose=True,
        )

        assert paths == []

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core.time.sleep")
    def test_respects_limit(self, mock_sleep, mock_search, sample_paper, tmp_output_dir):
        mock_search.return_value = [sample_paper]

        run_research(
            query="transformer",
            limit=3,
            output_dir=tmp_output_dir,
            api_key="",
            download_pdfs=False,
            verbose=False,
        )

        # Only 1 paper returned from mock, so 1 call
        mock_search.assert_called_once_with("transformer", max_results=3)

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core._download_pdf")
    @patch("research_loop.core.extract_pdf_text")
    @patch("research_loop.core.ai_generate_pnote_draft")
    @patch("research_loop.core.time.sleep")
    def test_download_pdfs_false_skips_download(
        self, mock_sleep, mock_draft, mock_extract, mock_dl, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]

        run_research(
            query="transformer",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="",
            download_pdfs=False,
            verbose=False,
        )

        # _download_pdf should have been skipped (download_pdfs=False)
        mock_dl.assert_not_called()

    @pytest.mark.no_freeze
    @patch("research_loop.core.search_arxiv")
    @patch("research_loop.core._download_pdf")
    @patch("research_loop.core.extract_pdf_text")
    @patch("research_loop.core.ai_generate_pnote_draft")
    @patch("research_loop.core.time.sleep")
    def test_custom_tags_passed_to_note(
        self, mock_sleep, mock_draft, mock_extract, mock_dl, mock_search, sample_paper, tmp_output_dir
    ):
        mock_search.return_value = [sample_paper]
        mock_extract.return_value = "Text."
        mock_draft.return_value = "Draft."

        paths = run_research(
            query="transformer",
            limit=5,
            output_dir=tmp_output_dir,
            api_key="test-key",
            download_pdfs=True,
            skip_existing=True,
            tags=["LLM", "Transformers"],
        )

        note_text = paths[0].read_text(encoding="utf-8")
        assert "**Tags:** LLM, Transformers" in note_text
