"""Tier 2 unit tests — llm/journal.py, pure functions, no I/O."""
import pytest
from llm.journal import JournalEntry


# =============================================================================
# JournalEntry dataclass tests
# =============================================================================
class TestJournalEntryInit:
    """Test JournalEntry dataclass."""

    def test_required_fields(self):
        """Required fields: id, content."""
        entry = JournalEntry(id="abc", content="Did research today")
        assert entry.id == "abc"
        assert entry.content == "Did research today"

    def test_optional_fields_default(self):
        """Optional fields have defaults."""
        entry = JournalEntry(id="x", content="C")
        # created_at is auto-generated by __post_init__ (not "" since not "" evaluates True)
        assert entry.updated_at == ""   # truly defaulted
        assert entry.tags == []
        assert entry.question_id == ""
        assert entry.experiment_id == ""
        assert entry.paper_id == ""
        assert entry.mood == ""
        assert entry.highlights == []

    def test_all_fields_can_be_set(self):
        """All fields can be set."""
        entry = JournalEntry(
            id="xyz",
            content="Deep work session",
            created_at="2026-01-01T10:00:00",
            updated_at="2026-01-01T12:00:00",
            tags=["focused", "productive"],
            question_id="q1",
            experiment_id="e1",
            paper_id="p1",
            mood="productive",
            highlights=["insight1", "insight2"],
        )
        assert entry.created_at == "2026-01-01T10:00:00"
        assert entry.updated_at == "2026-01-01T12:00:00"
        assert entry.tags == ["focused", "productive"]
        assert entry.question_id == "q1"
        assert entry.experiment_id == "e1"
        assert entry.paper_id == "p1"
        assert entry.mood == "productive"
        assert entry.highlights == ["insight1", "insight2"]


class TestJournalEntryPostInit:
    """Test JournalEntry.__post_init__."""

    def test_empty_created_at_triggers_auto_timestamp(self):
        """Empty created_at triggers auto-generation."""
        entry = JournalEntry(id="x", content="C")
        assert entry.created_at != ""
        # Should be ISO format
        assert "T" in entry.created_at

    def test_non_empty_created_at_preserved(self):
        """Non-empty created_at is preserved."""
        entry = JournalEntry(id="x", content="C", created_at="2025-01-01T00:00:00")
        assert entry.created_at == "2025-01-01T00:00:00"


# =============================================================================
# to_dict / from_dict tests
# =============================================================================
class TestJournalEntryDictConversion:
    """Test to_dict and from_dict."""

    def test_to_dict_includes_all_fields(self):
        """to_dict returns all fields as dict."""
        entry = JournalEntry(
            id="test-id",
            content="Test content",
            created_at="2026-01-01T10:00:00",
            updated_at="2026-01-02T11:00:00",
            tags=["tag1"],
            question_id="q1",
            experiment_id="e1",
            paper_id="p1",
            mood="excited",
            highlights=["h1"],
        )
        d = entry.to_dict()
        assert d["id"] == "test-id"
        assert d["content"] == "Test content"
        assert d["created_at"] == "2026-01-01T10:00:00"
        assert d["updated_at"] == "2026-01-02T11:00:00"
        assert d["tags"] == ["tag1"]
        assert d["question_id"] == "q1"
        assert d["experiment_id"] == "e1"
        assert d["paper_id"] == "p1"
        assert d["mood"] == "excited"
        assert d["highlights"] == ["h1"]

    def test_from_dict_reconstructs_entry(self):
        """from_dict reconstructs entry from dict."""
        data = {
            "id": "recon",
            "content": "Reconstructed",
            "created_at": "2026-02-15T08:00:00",
            "updated_at": "2026-02-15T10:00:00",
            "tags": ["a", "b"],
            "question_id": "q2",
            "experiment_id": "e2",
            "paper_id": "p2",
            "mood": "stuck",
            "highlights": ["x"],
        }
        entry = JournalEntry.from_dict(data)
        assert entry.id == "recon"
        assert entry.content == "Reconstructed"
        assert entry.created_at == "2026-02-15T08:00:00"
        assert entry.updated_at == "2026-02-15T10:00:00"
        assert entry.tags == ["a", "b"]
        assert entry.question_id == "q2"
        assert entry.experiment_id == "e2"
        assert entry.paper_id == "p2"
        assert entry.mood == "stuck"
        assert entry.highlights == ["x"]

    def test_from_dict_to_dict_roundtrip(self):
        """Roundtrip through from_dict then to_dict preserves data."""
        original = JournalEntry(
            id="round",
            content="Roundtrip test",
            tags=["test"],
            mood="neutral",
        )
        # Force created_at so roundtrip is stable
        original.created_at = "2026-03-01T09:00:00"
        d = original.to_dict()
        reconstructed = JournalEntry.from_dict(d)
        assert reconstructed.id == original.id
        assert reconstructed.content == original.content
        assert reconstructed.created_at == original.created_at
        assert reconstructed.tags == original.tags
        assert reconstructed.mood == original.mood

    def test_to_dict_empty_lists_and_strings(self):
        """Empty optional fields are included in dict."""
        entry = JournalEntry(id="e", content="C")
        d = entry.to_dict()
        assert d["tags"] == []
        assert d["highlights"] == []
        assert d["question_id"] == ""
        assert d["mood"] == ""


# =============================================================================
# Mood icons (render_list helper)
# =============================================================================
class TestMoodIcons:
    """Test mood icon mapping used in render_list."""

    def _mood_icon(self, mood: str) -> str:
        """Replicate mood icon logic."""
        return {"productive": "⚡", "stuck": "😓", "excited": "🎉", "neutral": "📝"}.get(mood, "📝")

    def test_known_moods(self):
        """Known moods map to correct icons."""
        assert self._mood_icon("productive") == "⚡"
        assert self._mood_icon("stuck") == "😓"
        assert self._mood_icon("excited") == "🎉"
        assert self._mood_icon("neutral") == "📝"

    def test_unknown_mood_defaults_to_memo(self):
        """Unknown mood defaults to memo icon."""
        assert self._mood_icon("unknown") == "📝"
        assert self._mood_icon("") == "📝"
        assert self._mood_icon("happy") == "📝"


# =============================================================================
# list_entries filtering logic
# =============================================================================
class TestListEntriesFilter:
    """Test list_entries filtering logic."""

    def _make_entry(self, id_, created_at, tags=None, question_id="", experiment_id="", content="entry"):
        """Helper to create JournalEntry with specific fields."""
        entry = JournalEntry(id=id_, content=content, created_at=created_at)
        if tags:
            entry.tags = tags
        entry.question_id = question_id
        entry.experiment_id = experiment_id
        return entry

    def _filter_entries(self, entries, tag="", question_id="", experiment_id="", today=False, days=0):
        """Replicate list_entries filtering."""
        # Simulate today filter
        today_str = "2026-04-27"
        result = list(entries)

        if today:
            result = [e for e in result if e.created_at.startswith(today_str)]
        elif days > 0:
            cutoff = "2026-04-27T00:00:00"
            # approximate: entries from last `days` days
            # For testing, use days filter
            cutoff_iso = f"2026-04-{27 - days + 1:02d}T00:00:00"
            result = [e for e in result if e.created_at >= cutoff_iso]

        if tag:
            result = [e for e in result if tag in e.tags]
        if question_id:
            result = [e for e in result if e.question_id == question_id]
        if experiment_id:
            result = [e for e in result if e.experiment_id == experiment_id]

        result.sort(key=lambda x: x.created_at, reverse=True)
        return result

    def test_filter_by_tag(self):
        """Tag filter keeps matching entries."""
        entries = [
            self._make_entry("1", "2026-04-01T10:00:00", tags=["research"]),
            self._make_entry("2", "2026-04-02T10:00:00", tags=["review"]),
            self._make_entry("3", "2026-04-03T10:00:00", tags=["research", "review"]),
        ]
        result = self._filter_entries(entries, tag="research")
        assert len(result) == 2
        assert {e.id for e in result} == {"1", "3"}

    def test_filter_by_question_id(self):
        """Question ID filter keeps matching entries."""
        entries = [
            self._make_entry("1", "2026-04-01T10:00:00", question_id="q1"),
            self._make_entry("2", "2026-04-02T10:00:00", question_id="q2"),
            self._make_entry("3", "2026-04-03T10:00:00", question_id="q1"),
        ]
        result = self._filter_entries(entries, question_id="q1")
        assert len(result) == 2
        assert {e.id for e in result} == {"1", "3"}

    def test_filter_by_experiment_id(self):
        """Experiment ID filter keeps matching entries."""
        entries = [
            self._make_entry("1", "2026-04-01T10:00:00", experiment_id="e1"),
            self._make_entry("2", "2026-04-02T10:00:00", experiment_id="e2"),
        ]
        result = self._filter_entries(entries, experiment_id="e1")
        assert len(result) == 1
        assert result[0].id == "1"

    def test_sort_by_date_descending(self):
        """Results are sorted by created_at descending."""
        entries = [
            self._make_entry("1", "2026-04-01T10:00:00"),
            self._make_entry("2", "2026-04-10T10:00:00"),
            self._make_entry("3", "2026-04-05T10:00:00"),
        ]
        result = self._filter_entries(entries)
        assert result[0].id == "2"  # April 10
        assert result[1].id == "3"  # April 5
        assert result[2].id == "1"  # April 1

    def test_limit_applied_after_sort(self):
        """Limit is applied after filtering and sorting."""
        entries = [
            self._make_entry(str(i), f"2026-04-{i:02d}T10:00:00")
            for i in range(1, 11)
        ]
        result = self._filter_entries(entries)
        # Just check sorting is preserved
        dates = [e.created_at for e in result]
        assert dates == sorted(dates, reverse=True)

    def test_combined_filters(self):
        """Multiple filters can be combined."""
        entries = [
            self._make_entry("1", "2026-04-01T10:00:00", tags=["research"], question_id="q1"),
            self._make_entry("2", "2026-04-02T10:00:00", tags=["research"], question_id="q2"),
            self._make_entry("3", "2026-04-03T10:00:00", tags=["review"], question_id="q1"),
        ]
        result = self._filter_entries(entries, tag="research", question_id="q1")
        assert len(result) == 1
        assert result[0].id == "1"

    def test_no_matches_returns_empty(self):
        """No matches returns empty list."""
        entries = [
            self._make_entry("1", "2026-04-01T10:00:00", tags=["review"]),
        ]
        result = self._filter_entries(entries, tag="nonexistent")
        assert result == []


# =============================================================================
# stats() logic
# =============================================================================
class TestStatsLogic:
    """Test stats() aggregation logic."""

    def _stats(self, entries) -> dict:
        """Replicate stats aggregation."""
        if not entries:
            return {"total": 0, "this_week": 0, "this_month": 0}

        now_iso = "2026-04-27T12:00:00"
        week_ago = "2026-04-20T12:00:00"
        month_ago = "2026-03-28T12:00:00"

        tags_count = {}
        mood_count = {}
        for e in entries:
            for t in e.tags:
                tags_count[t] = tags_count.get(t, 0) + 1
            if e.mood:
                mood_count[e.mood] = mood_count.get(e.mood, 0) + 1

        return {
            "total": len(entries),
            "this_week": len([e for e in entries if e.created_at >= week_ago]),
            "this_month": len([e for e in entries if e.created_at >= month_ago]),
            "top_tags": sorted(tags_count.items(), key=lambda x: -x[1])[:10],
            "mood_distribution": mood_count,
        }

    def test_empty_returns_zeros(self):
        """Empty entries returns zero counts."""
        result = self._stats([])
        assert result["total"] == 0
        assert result["this_week"] == 0
        assert result["this_month"] == 0

    def test_total_count(self):
        """Total counts all entries."""
        entries = [JournalEntry(id=str(i), content=f"E{i}") for i in range(5)]
        # Set dates spread across months
        for i, entry in enumerate(entries):
            entry.created_at = f"2026-0{(i % 3) + 1}-{10+i:02d}T10:00:00"
        result = self._stats(entries)
        assert result["total"] == 5

    def test_this_week_filter(self):
        """this_week counts entries from last 7 days."""
        entries = [
            JournalEntry(id="1", content="W", created_at="2026-04-27T10:00:00"),
            JournalEntry(id="2", content="W2", created_at="2026-04-25T10:00:00"),
            JournalEntry(id="3", content="O", created_at="2026-04-10T10:00:00"),  # 17 days ago
        ]
        result = self._stats(entries)
        assert result["this_week"] == 2

    def test_this_month_filter(self):
        """this_month counts entries from last 30 days."""
        entries = [
            JournalEntry(id="1", content="M", created_at="2026-04-27T10:00:00"),
            JournalEntry(id="2", content="M2", created_at="2026-04-01T10:00:00"),
            JournalEntry(id="3", content="O", created_at="2026-02-01T10:00:00"),  # old
        ]
        result = self._stats(entries)
        assert result["this_month"] == 2

    def test_top_tags_sorted_by_count(self):
        """top_tags sorted by count descending."""
        entries = [
            JournalEntry(id="1", content="E1", tags=["python", "ml"]),
            JournalEntry(id="2", content="E2", tags=["python", "research"]),
            JournalEntry(id="3", content="E3", tags=["python"]),
            JournalEntry(id="4", content="E4", tags=["research"]),
        ]
        result = self._stats(entries)
        top = result["top_tags"]
        assert top[0] == ("python", 3)
        assert top[1] == ("research", 2)

    def test_top_tags_limited_to_10(self):
        """top_tags limited to 10 items."""
        entries = [
            JournalEntry(id=str(i), content=f"E{i}", tags=[f"tag{i}"])
            for i in range(15)
        ]
        result = self._stats(entries)
        assert len(result["top_tags"]) == 10

    def test_mood_distribution(self):
        """mood_distribution counts each mood."""
        entries = [
            JournalEntry(id="1", content="E1", mood="productive"),
            JournalEntry(id="2", content="E2", mood="productive"),
            JournalEntry(id="3", content="E3", mood="stuck"),
            JournalEntry(id="4", content="E4", mood=""),  # empty mood ignored
        ]
        result = self._stats(entries)
        assert result["mood_distribution"]["productive"] == 2
        assert result["mood_distribution"]["stuck"] == 1
        assert "neutral" not in result["mood_distribution"]

    def test_empty_tags_no_top_tags_crash(self):
        """Empty tags doesn't cause top_tags to crash."""
        entries = [JournalEntry(id="1", content="E1", tags=[])]
        result = self._stats(entries)
        assert result["top_tags"] == []


# =============================================================================
# render_list tests
# =============================================================================
class TestRenderList:
    """Test render_list formatting."""

    def _render_list(self, entries, verbose=False):
        """Replicate render_list formatting."""
        if not entries:
            return "No journal entries."

        mood_icons = {"productive": "⚡", "stuck": "😓", "excited": "🎉", "neutral": "📝"}
        lines = []
        for e in entries:
            icon = mood_icons.get(e.mood, "📝")
            date = e.created_at[:10]
            lines.append(f"{icon} [{date}] {e.content[:80]}")
            if verbose:
                if e.tags:
                    lines.append(f"   Tags: {', '.join(e.tags)}")
                if e.question_id:
                    lines.append(f"   Question: {e.question_id}")
                if e.experiment_id:
                    lines.append(f"   Experiment: {e.experiment_id}")
        return '\n'.join(lines)

    def test_empty_returns_placeholder(self):
        """Empty list returns placeholder text."""
        assert self._render_list([]) == "No journal entries."

    def test_content_truncated_to_80_chars(self):
        """Content is truncated to 80 characters."""
        long_content = "X" * 100
        entry = JournalEntry(id="x", content=long_content, created_at="2026-04-01T10:00:00")
        output = self._render_list([entry])
        assert len(output.split('\n')[0]) <= 100  # icon + date + 80 chars

    def test_mood_icon_shown(self):
        """Mood icon is shown."""
        entry = JournalEntry(id="x", content="C", created_at="2026-04-01T10:00:00", mood="productive")
        output = self._render_list([entry])
        assert "⚡" in output

    def test_date_extracted_from_created_at(self):
        """Date is extracted from created_at."""
        entry = JournalEntry(id="x", content="C", created_at="2026-04-15T14:30:00")
        output = self._render_list([entry])
        assert "[2026-04-15]" in output

    def test_verbose_shows_tags(self):
        """Verbose mode shows tags."""
        entry = JournalEntry(id="x", content="C", created_at="2026-04-01T10:00:00", tags=["research", "ai"])
        output = self._render_list([entry], verbose=True)
        assert "Tags: research, ai" in output

    def test_verbose_shows_question_id(self):
        """Verbose mode shows question ID."""
        entry = JournalEntry(id="x", content="C", created_at="2026-04-01T10:00:00", question_id="q123")
        output = self._render_list([entry], verbose=True)
        assert "Question: q123" in output

    def test_verbose_shows_experiment_id(self):
        """Verbose mode shows experiment ID."""
        entry = JournalEntry(id="x", content="C", created_at="2026-04-01T10:00:00", experiment_id="e456")
        output = self._render_list([entry], verbose=True)
        assert "Experiment: e456" in output

    def test_multiple_entries(self):
        """Multiple entries are rendered."""
        entries = [
            JournalEntry(id="1", content="First entry", created_at="2026-04-01T10:00:00"),
            JournalEntry(id="2", content="Second entry", created_at="2026-04-02T10:00:00"),
        ]
        output = self._render_list(entries)
        assert "First entry" in output
        assert "Second entry" in output
        assert "[2026-04-01]" in output
        assert "[2026-04-02]" in output


# =============================================================================
# search() logic
# =============================================================================
class TestSearchLogic:
    """Test search filtering logic."""

    def _search(self, entries, query, limit=20):
        """Replicate search logic."""
        q = query.lower()
        result = [e for e in entries if q in e.content.lower()]
        result.sort(key=lambda x: x.created_at, reverse=True)
        return result[:limit]

    def test_empty_query_matches_all(self):
        """Empty query would match all (but real search uses non-empty)."""
        # The real implementation matches empty string in all content
        entries = [
            JournalEntry(id="1", content="Hello world"),
            JournalEntry(id="2", content="Goodbye"),
        ]
        result = self._search(entries, "")
        assert len(result) == 2

    def test_case_insensitive_match(self):
        """Search is case insensitive."""
        entries = [
            JournalEntry(id="1", content="TRANSFORMER Architecture"),
            JournalEntry(id="2", content="transformer model"),
        ]
        result = self._search(entries, "transformer")
        assert len(result) == 2

    def test_partial_match(self):
        """Partial text match works."""
        entries = [
            JournalEntry(id="1", content="Attention is all you need"),
            JournalEntry(id="2", content="Sparse attention"),
        ]
        result = self._search(entries, "attention")
        assert len(result) == 2

    def test_no_match_returns_empty(self):
        """No match returns empty list."""
        entries = [
            JournalEntry(id="1", content="Machine learning"),
        ]
        result = self._search(entries, "transformer")
        assert result == []

    def test_limit_applied(self):
        """Limit is applied to results."""
        entries = [JournalEntry(id=str(i), content=f"Entry {i}") for i in range(25)]
        result = self._search(entries, "Entry", limit=10)
        assert len(result) == 10

    def test_results_sorted_by_date_descending(self):
        """Results sorted by date descending."""
        entries = [
            JournalEntry(id="1", content="Old entry", created_at="2026-01-01T10:00:00"),
            JournalEntry(id="2", content="New entry", created_at="2026-04-01T10:00:00"),
            JournalEntry(id="3", content="Middle entry", created_at="2026-03-01T10:00:00"),
        ]
        result = self._search(entries, "entry")
        assert result[0].id == "2"  # newest first
        assert result[1].id == "3"
        assert result[2].id == "1"
